# Generated by Django 4.1.2 on 2022-10-28 19:44

from django.db import migrations, models
import exam_prep_1.game_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Board/Card Game', 'Board/Card Game'), ('Other', 'Other')], max_length=15)),
                ('rating', models.FloatField(validators=[exam_prep_1.game_app.models.min_rating_validator, exam_prep_1.game_app.models.max_rating_validator])),
                ('max_level', models.IntegerField(blank=True, null=True, validators=[exam_prep_1.game_app.models.max_level_validator], verbose_name='Max Level')),
                ('image_url', models.ImageField(upload_to='')),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
